#!/usr/bin/env php
<?php

use Illuminate\Foundation\Application;
use Illuminate\Foundation\Console\Kernel;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Output\ConsoleOutput;

define('LARAVEL_START', microtime(true));

require __DIR__.'/vendor/autoload.php';

$status = require_once __DIR__.'/bootstrap/app.php';

$kernel = $status->make(Kernel::class);

$status = $kernel->handle(
    $input = new ArgvInput,
    new ConsoleOutput,
);

if (! is_int($status)) {
    $status = match ($status) {
        true => 0,
        default => 1,
    };
}

$kernel->terminate($input, $status);

exit($status);
